### ISSUE TITLE
code bug(timm.models.vision_transformer)

### ISSUE THREAD

**Issue by 1009073362** [TOM-tym/APG#2]
The required version of timm is 0.5.4. If you type dir(vision_transformer), you will only see 'get_init_weights_vit', 'init_weights_vit_jax', 'init_weights_vit_moco', 'init_weights_vit_timm'. However, in the file 'Self_Prompts.py', on line 8, the author wrote 'from timm.models.vision_transformer import _init_vit_weights'. Is this a mistake? Which one should we choose?I would be very grateful if you could answer my questions

**Comment by TOM-tym** [comment]
Hi, the 0.5.4 version of timm package contains method `_init_vit_weights` (see Commit [e0c4eec](https://github.com/huggingface/pytorch-image-models/blob/e0c4eec4b66dc14ae96097c7b4a7ef2af45ba309/timm/models/vision_transformer.py#L376) of the timm repo), please make sure you've installed the corrected version.
